=== Raicuparta/rai-pal-db/mod-db/1/schema/mod-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"id": {
			"type": "string",
			"description": "Unique identifier for this mod. Must be globally unique within all mods from all loaders."
		},
		"loaderId": {
			"type": "string",
			"enum": ["bepinex", "ue4ss", "runnable"],
			"description": "ID of the mod loader required to use this mod. If not set, assumed to be compatible with any loader."
		},
		"isLoader": {
			"type": "boolean",
			"description": "Whether this mod is a mod loader, meaning it is required to install one of these to be able to use any of the mods in this library."
		},
		"deprecated": {
			"type": "boolean",
			"description": "If true, users should be warned about it and invited to uninstall this mod, and directed to install the appropriate replacement."
		},
		"redownloadId": {
			"type": "number",
			"description": "Increment this number to force clients to redownload this mod. Useful when a mod needs to be redownloaded without a new version being released."
		},
		"engine": {
			"type": "string",
			"enum": ["Unity", "Unreal", "Godot"],
			"description": "Game engine that this mod supports."
		},
		"architecture": {
			"type": "string",
			"enum": ["X64", "X86"],
			"description": "Whether this mod is only compatible with 64-bit or 32-bit (x86) games. If not set, assumed to be compatible with both."
		},
		"unityBackend": {
			"type": "string",
			"enum": ["Il2Cpp", "Mono"],
			"description": "Only relevant if engine=Unity. Scripting backend used by the game."
		},
		"title": {
			"type": "string",
			"description": "Mod's display name."
		},
		"author": {
			"type": "string",
			"description": "Mod author."
		},
		"sourceCode": {
			"type": "string",
			"format": "uri",
			"description": "URL of a repository with the mod's source code."
		},
		"description": {
			"type": "string",
			"description": "Short description that explains what the mod does."
		},
		"github": {
			"$ref": "./github-schema.json"
		},
		"latestVersion": {
			"$ref": "./release-schema.json"
		},
		"root": {
			"type": "string",
			"description": "Optional, path of the root folder within the zip."
		},
		"engineVersionRange": {
			"type": "object",
			"properties": {
				"minimum": {
					"$ref": "./engine-version-schema.json"
				},
				"maximum": {
					"$ref": "./engine-version-schema.json"
				}
			}
		},
		"configs": {
			"type": "object",
			"description": "Information used to find local mod configs, and also for downloading configs from the database.",
			"properties": {
				"destinationPath": {
					"type": "string",
					"description": "Path in the user's PC where the config is installed to. This path can be relative to something, depending on the mod loader."
				},
				"destinationType": {
					"type": "string",
					"description": "If file, the downloaded config will be placed directly in the installTo path. If folder, the downloaded file must be a zip, and gets extracted to the destination path, which must be a folder.",
					"enum": ["File", "Folder"]
				},
				"modIdOverride": {
					"type": "string",
					"description": "If set, overrides the mod ID used for finding config files. Useful when multiple mods use the same configs."
				}
			},
			"required": ["destinationPath", "destinationType"],
			"additionalProperties": false
		}
	},
	"additionalProperties": false,
	"required": ["id", "loaderId", "title", "author", "sourceCode", "description"]
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/runtime-unity-editor-mono/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "runtime-unity-editor-mono",
	"loaderId": "bepinex",
	"engine": "Unity",
	"unityBackend": "Mono",
	"title": "Runtime Unity Editor",
	"author": "ManlyMarco",
	"sourceCode": "https://github.com/ManlyMarco/RuntimeUnityEditor",
	"description": "In-game inspector and debugging tools. May work on games where UnityExplorer fails.",
	"latestVersion": {
		"id": "5.2.1",
		"url": "https://github.com/ManlyMarco/RuntimeUnityEditor/releases/download/v5.2.1/RuntimeUnityEditor_BepInEx5_v5.2.1.zip",
		"root": "BepInEx"
	}
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/uuvr-mono-legacy/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "uuvr-mono-legacy",
	"loaderId": "bepinex",
	"engine": "Unity",
	"unityBackend": "Mono",
	"title": "UUVR Mono Legacy",
	"author": "Raicuparta",
	"sourceCode": "https://github.com/Raicuparta/uuvr",
	"description": "Uses OpenVR. Start SteamVR before starting the game. Use the Configuration Manager mod to change UUVR settings for each game.",
	"engineVersionRange": {
		"maximum": {
			"major": 2019
		}
	},
	"latestVersion": {
		"id": "0.3.1",
		"url": "https://github.com/Raicuparta/uuvr/releases/download/v0.3.1/uuvr-mono-legacy.zip"
	}
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/unity-explorer-mono/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "unity-explorer-mono",
	"loaderId": "bepinex",
	"engine": "Unity",
	"unityBackend": "Mono",
	"title": "UnityExplorer Mono",
	"author": "Sinai",
	"sourceCode": "https://github.com/sinai-dev/UnityExplorer",
	"description": "An in-game UI for exploring, debugging and modifying Unity games.",
	"latestVersion": {
		"id": "4.9.0",
		"url": "https://github.com/sinai-dev/UnityExplorer/releases/download/4.9.0/UnityExplorer.BepInEx5.Mono.zip"
	}
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/unity-explorer-il2cpp/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "unity-explorer-il2cpp",
	"loaderId": "bepinex",
	"engine": "Unity",
	"unityBackend": "Il2Cpp",
	"title": "UnityExplorer Il2Cpp",
	"author": "Sinai",
	"sourceCode": "https://github.com/sinai-dev/UnityExplorer",
	"description": "An in-game UI for exploring, debugging and modifying Unity games. Not compatible with Config Manager.",
	"latestVersion": {
		"id": "4.12.1",
		"url": "https://github.com/yukieiji/UnityExplorer/releases/download/v4.12.1/UnityExplorer.BepInEx.Unity.IL2CPP.CoreCLR.zip"
	}
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/uuvr-il2cpp-legacy/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "uuvr-il2cpp-legacy",
	"loaderId": "bepinex",
	"engine": "Unity",
	"unityBackend": "Il2Cpp",
	"title": "UUVR Il2Cpp Legacy",
	"author": "Raicuparta",
	"sourceCode": "https://github.com/Raicuparta/uuvr",
	"description": "Uses OpenVR. Start SteamVR before starting the game. Use the Configuration Manager mod to change UUVR settings for each game.",
	"engineVersionRange": {
		"maximum": {
			"major": 2019
		}
	},
	"latestVersion": {
		"id": "0.3.1",
		"url": "https://github.com/Raicuparta/uuvr/releases/download/v0.3.1/uuvr-il2cpp-legacy.zip"
	}
}
