=== Raicuparta/rai-pal-db/mod-db/1/schema/mod-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"id": {
			"type": "string",
			"description": "Unique identifier for this mod. Must be globally unique within all mods from all loaders."
		},
		"loaderId": {
			"type": "string",
			"enum": ["bepinex", "ue4ss", "runnable"],
			"description": "ID of the mod loader required to use this mod. If not set, assumed to be compatible with any loader."
		},
		"isLoader": {
			"type": "boolean",
			"description": "Whether this mod is a mod loader, meaning it is required to install one of these to be able to use any of the mods in this library."
		},
		"deprecated": {
			"type": "boolean",
			"description": "If true, users should be warned about it and invited to uninstall this mod, and directed to install the appropriate replacement."
		},
		"redownloadId": {
			"type": "number",
			"description": "Increment this number to force clients to redownload this mod. Useful when a mod needs to be redownloaded without a new version being released."
		},
		"engine": {
			"type": "string",
			"enum": ["Unity", "Unreal", "Godot"],
			"description": "Game engine that this mod supports."
		},
		"architecture": {
			"type": "string",
			"enum": ["X64", "X86"],
			"description": "Whether this mod is only compatible with 64-bit or 32-bit (x86) games. If not set, assumed to be compatible with both."
		},
		"unityBackend": {
			"type": "string",
			"enum": ["Il2Cpp", "Mono"],
			"description": "Only relevant if engine=Unity. Scripting backend used by the game."
		},
		"title": {
			"type": "string",
			"description": "Mod's display name."
		},
		"author": {
			"type": "string",
			"description": "Mod author."
		},
		"sourceCode": {
			"type": "string",
			"format": "uri",
			"description": "URL of a repository with the mod's source code."
		},
		"description": {
			"type": "string",
			"description": "Short description that explains what the mod does."
		},
		"github": {
			"$ref": "./github-schema.json"
		},
		"latestVersion": {
			"$ref": "./release-schema.json"
		},
		"root": {
			"type": "string",
			"description": "Optional, path of the root folder within the zip."
		},
		"engineVersionRange": {
			"type": "object",
			"properties": {
				"minimum": {
					"$ref": "./engine-version-schema.json"
				},
				"maximum": {
					"$ref": "./engine-version-schema.json"
				}
			}
		},
		"configs": {
			"type": "object",
			"description": "Information used to find local mod configs, and also for downloading configs from the database.",
			"properties": {
				"destinationPath": {
					"type": "string",
					"description": "Path in the user's PC where the config is installed to. This path can be relative to something, depending on the mod loader."
				},
				"destinationType": {
					"type": "string",
					"description": "If file, the downloaded config will be placed directly in the installTo path. If folder, the downloaded file must be a zip, and gets extracted to the destination path, which must be a folder.",
					"enum": ["File", "Folder"]
				},
				"modIdOverride": {
					"type": "string",
					"description": "If set, overrides the mod ID used for finding config files. Useful when multiple mods use the same configs."
				}
			},
			"required": ["destinationPath", "destinationType"],
			"additionalProperties": false
		}
	},
	"additionalProperties": false,
	"required": ["id", "loaderId", "title", "author", "sourceCode", "description"]
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/bepinex-mono-x86/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "bepinex-mono-x86",
	"loaderId": "bepinex",
	"isLoader": true,
	"engine": "Unity",
	"architecture": "X86",
	"unityBackend": "Mono",
	"title": "BepInEx Mono X86",
	"author": "BepInEx",
	"sourceCode": "https://github.com/BepInEx/BepInEx",
	"description": "BepInEx stable Mono build for X86 games.",
	"latestVersion": {
		"id": "5.4.23.5",
		"url": "https://github.com/BepInEx/BepInEx/releases/download/v5.4.23.5/BepInEx_win_x86_5.4.23.5.zip"
	}
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/bepinex-il2cpp-x86/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "bepinex-il2cpp-x86",
	"loaderId": "bepinex",
	"isLoader": true,
	"engine": "Unity",
	"architecture": "X86",
	"unityBackend": "Il2Cpp",
	"title": "BepInEx Il2Cpp X86",
	"author": "BepInEx",
	"sourceCode": "https://github.com/BepInEx/BepInEx",
	"description": "BepInEx bleeding-edge Il2Cpp build for X86 games.",
	"latestVersion": {
		"id": "6.0.0-be.755",
		"url": "https://builds.bepinex.dev/projects/bepinex_be/755/BepInEx-Unity.IL2CPP-win-x86-6.0.0-be.755%2B3fab71a.zip"
	}
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/config-manager-mono/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "config-manager-mono",
	"loaderId": "bepinex",
	"engine": "Unity",
	"unityBackend": "Mono",
	"title": "Config Manager Mono",
	"author": "sinai",
	"sourceCode": "https://github.com/sinai-dev/BepInExConfigManager",
	"description": "Press F5 to show an in-game menu for changing mod settings. Use this with UUVR.",
	"latestVersion": {
		"id": "1.3.0",
		"url": "https://github.com/sinai-dev/BepInExConfigManager/releases/download/1.3.0/BepInExConfigManager.Mono.zip"
	}
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/ue4ss/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "ue4ss",
	"loaderId": "ue4ss",
	"isLoader": true,
	"engine": "Unreal",
	"title": "UE4SS",
	"author": "UE4SS-RE",
	"sourceCode": "https://github.com/UE4SS-RE/RE-UE4SS",
	"description": "Scripting and modding framework for Unreal Engine games.",
	"latestVersion": {
		"id": "v3.0.1-949",
		"url": "https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v3.0.1-949-gdd6777a8.zip"
	}
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/everyone-il2cpp/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "everyone-il2cpp",
	"loaderId": "bepinex",
	"engine": "Unity",
	"unityBackend": "Il2Cpp",
	"title": "Everyone",
	"author": "Raicuparta",
	"sourceCode": "https://github.com/Raicuparta/everyone",
	"description": "IL2CPP version. Work in progress! F3 to chat.",
	"latestVersion": {
		"id": "0.1.0",
		"url": "https://github.com/Raicuparta/rai-pal-db/releases/download/everyone-v0.1.0/EveryoneClient.BepInEx.Unity.IL2CPP.CoreCLR.zip"
	},
	"configs": {
		"destinationPath": "config/raicuparta.everyone.json",
		"destinationType": "File"
	}
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/everyone-mono-legacy/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "everyone-mono-legacy",
	"loaderId": "bepinex",
	"engine": "Unity",
	"engineVersionRange": {
		"maximum": {
			"major": 5
		}
	},
	"unityBackend": "Mono",
	"title": "Everyone (Legacy)",
	"author": "Raicuparta",
	"sourceCode": "https://github.com/Raicuparta/everyone",
	"description": "Mono Legacy version. Work in progress! F3 to chat.",
	"latestVersion": {
		"id": "0.1.0",
		"url": "https://github.com/Raicuparta/rai-pal-db/releases/download/everyone-v0.1.0/EveryoneClient.BepInEx5.Mono.Legacy.zip"
	},
	"configs": {
		"destinationPath": "config/raicuparta.everyone.json",
		"destinationType": "File"
	}
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/config-manager-il2cpp/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "config-manager-il2cpp",
	"loaderId": "bepinex",
	"engine": "Unity",
	"unityBackend": "Il2Cpp",
	"title": "Config Manager IL2CPP",
	"author": "sinai",
	"sourceCode": "https://github.com/Vapok/BepInExConfigManager",
	"description": "Press F5 to show an in-game menu for changing mod settings. Use this with UUVR. Not compatible with UnityExplorer.",
	"latestVersion": {
		"id": "1.0.0",
		"url": "https://github.com/Vapok/BepInExConfigManager/releases/download/v1.0.0/Vapok-BepInExConfigManager-1.0.0.zip"
	}
}

=== Raicuparta/rai-pal-db/mod-db/1/mods/uuvr-mono-modern/mod.json
{
	"$schema": "../../schema/mod-schema.json",
	"id": "uuvr-mono-modern",
	"loaderId": "bepinex",
	"engine": "Unity",
	"unityBackend": "Mono",
	"title": "UUVR Mono Modern",
	"author": "Raicuparta",
	"sourceCode": "https://github.com/Raicuparta/uuvr",
	"description": "Supports OpenXR and OpenVR. Use the Configuration Manager mod to change UUVR settings for each game.",
	"engineVersionRange": {
		"minimum": {
			"major": 2018,
			"minor": 4
		}
	},
	"latestVersion": {
		"id": "0.4.0",
		"url": "https://github.com/Raicuparta/uuvr/releases/download/v0.4.0/uuvr-mono-modern.zip"
	},
	"configs": {
		"destinationPath": "config/raicuparta.uuvr-modern.cfg",
		"destinationType": "File"
	}
}
